# Generated by Django 3.2.12 on 2022-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Section',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
