# Generated by Django 3.2.12 on 2022-02-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0002_auto_20220208_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='classs',
        ),
        migrations.DeleteModel(
            name='Publicnotice',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
