# Generated by Django 3.2.12 on 2022-02-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentmanage', '0003_auto_20220209_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=150, null=True)),
                ('Section', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeTitle', models.CharField(max_length=150, null=True)),
                ('NoticeMsg', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('StuID', models.IntegerField(null=True)),
                ('FatherName', models.CharField(max_length=150, null=True)),
                ('MotherName', models.CharField(max_length=150, null=True)),
                ('ContactNumber', models.CharField(max_length=150, null=True)),
                ('AltenateNumber', models.CharField(max_length=150, null=True)),
                ('Address', models.CharField(max_length=150, null=True)),
                ('UserName', models.CharField(max_length=150, null=True)),
                ('Image', models.FileField(max_length=200, null=True, upload_to='')),
                ('DateofAdmission', models.DateField(null=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmanage.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeTitle', models.CharField(max_length=150, null=True)),
                ('NoticeMsg', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmanage.class')),
            ],
        ),
    ]
