# Generated by Django 3.2.12 on 2022-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0004_class_notice_publicnotice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StuID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
